export const USER_REPO = Symbol('USER_REPOSITORY');

export const USER_PROFILE_REPO = Symbol('USER_PROFILE_REPOSITORY');

export const CHANGE_PASSWORD_TOKEN_REPO = Symbol(
  'CHANGE_PASSWORD_TOKEN_REPOSITORY',
);

export const CHANGE_EMAIL_TOKEN_REPO = Symbol('CHANGE_EMAIL_TOKEN_REPOSITORY');

export const EMAIL_VERIFICATION_TOKEN_REPO = Symbol(
  'EMAIL_VERIFICATION_TOKEN_REPOSITORY',
);
